name: emacs-tealeg
version: 24.5
summary: GNU Emacs 24.5
description: An extensible, customizable, free/libre text editor -- and more.
confinement: strict

apps:
  emacs-tealeg:
    command: emacs-tealeg
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
  emacsclient-tealeg:
    command: emacsclient-tealeg
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
  ctags:
    command: ctags
  ebrowse:
    command: ebrowse
  etags:
    command: etags
  grep-changelog:
    command: grep-changelog

parts:
  emacs-tealeg:
    plugin: copy
    files:
      emacs-tealeg.sh: bin/emacs-tealeg
      emacsclient-tealeg.sh: bin/emacsclient-tealeg
  emacs:
    plugin: autotools
    source: http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.xz
    source-type: tar
    install-via: prefix
    build-packages:
      - libgif-dev
      - libxpm-dev
      - libjpeg-dev
      - libtiff5-dev
      - libncursesw5-dev
      - libsm-dev
      - libxft-dev
    stage-packages:
      - libgif7
      - libxpm4
      - libjpeg8
      - libtiff5
      - libncursesw5
      - libsm6
      - libxft2
    after:
      - desktop/gtk3
