name: emacs-tealeg
version: 25.2
summary: GNU Emacs 25.2
description: An extensible, customizable, free/libre text editor -- and more.
grade: stable
confinement: strict

apps:
  emacs-tealeg:
    command: emacs-tealeg
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
  emacsclient-tealeg:
    command: emacsclient-tealeg
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
  ctags:
    command: ctags
  ebrowse:
    command: ebrowse
  etags:
    command: etags

parts:
  emacs-tealeg:
    plugin: dump
    source: scripts
    organize:
        emacs-tealeg.sh: bin/emacs-tealeg
        emacsclient-tealeg.sh: bin/emacsclient-tealeg
  emacs:
    plugin: autotools
    source: http://ftpmirror.gnu.org/emacs/emacs-25.2.tar.xz
    source-type: tar
    install-via: prefix
    build-packages:
      - libgnutls-dev
      - libgif-dev
      - libxpm-dev
      - libjpeg-dev
      - libtiff5-dev
      - libncursesw5-dev
      - libsm-dev
      - libxft-dev
    stage-packages:
      - libgnutls30
      - libgif7
      - libxpm4
      - libjpeg8
      - libtiff5
      - libncursesw5
      - libsm6
      - libxft2
    after:
      - desktop-gtk3
